export const Pays:{ [key: string]:  PaysOption} = {
  Afghanistan: { name: 'Afghanistan', value: 'Afghanistan' },
  Afrique_du_Sud: { name: 'Afrique du Sud', value: 'Afrique du Sud' },
  Albanie: { name: 'Albanie', value: 'Albanie' },
  Algérie: { name: 'Algérie', value: 'Algérie' },
  Allemagne: { name: 'Allemagne', value: 'Allemagne' },
  Andorre: { name: 'Andorre', value: 'Andorre' },
  Angola: { name: 'Angola', value: 'Angola' },
  Antigua_et_Barbuda: { name: 'Antigua-et-Barbuda', value: 'Antigua-et-Barbuda' },
  Arabie_saoudite: { name: 'Arabie saoudite', value: 'Arabie saoudite' },
  Argentine: { name: 'Argentine', value: 'Argentine' },
  Arménie: { name: 'Arménie', value: 'Arménie' },
  Australie: { name: 'Australie', value: 'Australie' },
  Autriche: { name: 'Autriche', value: 'Autriche' },
  Azerbaïdjan: { name: 'Azerbaïdjan', value: 'Azerbaïdjan' },
  Bahamas: { name: 'Bahamas', value: 'Bahamas' },
  Bahreïn: { name: 'Bahreïn', value: 'Bahreïn' },
  Bangladesh: { name: 'Bangladesh', value: 'Bangladesh' },
  Barbade: { name: 'Barbade', value: 'Barbade' },
  Belgique: { name: 'Belgique', value: 'Belgique' },
  Belize: { name: 'Belize', value: 'Belize' },
  Bénin: { name: 'Bénin', value: 'Bénin' },
  Bhoutan: { name: 'Bhoutan', value: 'Bhoutan' },
  Biélorussie: { name: 'Biélorussie', value: 'Biélorussie' },
  Birmanie: { name: 'Birmanie', value: 'Birmanie' },
  Bolivie: { name: 'Bolivie', value: 'Bolivie' },
  Bosnie_Herzégovine: { name: 'Bosnie-Herzégovine', value: 'Bosnie-Herzégovine' },
  Botswana: { name: 'Botswana', value: 'Botswana' },
  Brésil: { name: 'Brésil', value: 'Brésil' },
  Brunei: { name: 'Brunei', value: 'Brunei' },
  Bulgarie: { name: 'Bulgarie', value: 'Bulgarie' },
  Burkina_Faso: { name: 'Burkina Faso', value: 'Burkina Faso' },
  Burundi: { name: 'Burundi', value: 'Burundi' },
  Cambodge: { name: 'Cambodge', value: 'Cambodge' },
  Cameroun: { name: 'Cameroun', value: 'Cameroun' },
  Canada: { name: 'Canada', value: 'Canada' },
  Cap_Vert: { name: 'Cap-Vert', value: 'Cap-Vert' },
  Centrafrique: { name: 'Centrafrique', value: 'Centrafrique' },
  Chili: { name: 'Chili', value: 'Chili' },
  Chine: { name: 'Chine', value: 'Chine' },
  Chypre: { name: 'Chypre', value: 'Chypre' },
  Colombie: { name: 'Colombie', value: 'Colombie' },
  Comores: { name: 'Comores', value: 'Comores' },
  Congo_Brazzaville: { name: 'Congo-Brazzaville', value: 'Congo-Brazzaville' },
  Congo_Kinshasa: { name: 'Congo-Kinshasa', value: 'Congo-Kinshasa' },
  Corée_du_Nord: { name: 'Corée du Nord', value: 'Corée du Nord' },
  Corée_du_Sud: { name: 'Corée du Sud', value: 'Corée du Sud' },
  Costa_Rica: { name: 'Costa Rica', value: 'Costa Rica' },
  Côte_d_Ivoire: { name: "Côte d'Ivoire", value: "Côte d'Ivoire" },
  Croatie: { name: 'Croatie', value: 'Croatie' },
  Cuba: { name: 'Cuba', value: 'Cuba' },
  Danemark: { name: 'Danemark', value: 'Danemark' },
  Djibouti: { name: 'Djibouti', value: 'Djibouti' },
  Dominique: { name: 'Dominique', value: 'Dominique' },
  Égypte: { name: 'Égypte', value: 'Égypte' },
  Émirats_Arabes_Unis: { name: 'Émirats arabes unis', value: 'Émirats arabes unis' },
  Équateur: { name: 'Équateur', value: 'Équateur' },
  Érythrée: { name: 'Érythrée', value: 'Érythrée' },
  Espagne: { name: 'Espagne', value: 'Espagne' },
  Estonie: { name: 'Estonie', value: 'Estonie' },
  Eswatini: { name: 'Eswatini', value: 'Eswatini' },
  États_Unis: { name: 'États-Unis', value: 'États-Unis' },
  Éthiopie: { name: 'Éthiopie', value: 'Éthiopie' },
  Fidji: { name: 'Fidji', value: 'Fidji' },
  Finlande: { name: 'Finlande', value: 'Finlande' },
  France: { name: 'France', value: 'France' },
  Gabon: { name: 'Gabon', value: 'Gabon' },
  Gambie: { name: 'Gambie', value: 'Gambie' },
  Géorgie: { name: 'Géorgie', value: 'Géorgie' },
  Ghana: { name: 'Ghana', value: 'Ghana' },
  Grèce: { name: 'Grèce', value: 'Grèce' },
  Grenade: { name: 'Grenade', value: 'Grenade' },
  Guatemala: { name: 'Guatemala', value: 'Guatemala' },
  Guinée: { name: 'Guinée', value: 'Guinée' },
  Guinée_Bissao: { name: 'Guinée-Bissao', value: 'Guinée-Bissao' },
  Guinée_Équatoriale: { name: 'Guinée équatoriale', value: 'Guinée équatoriale' },
  Guyana: { name: 'Guyana', value: 'Guyana' },
  Haïti: { name: 'Haïti', value: 'Haïti' },
  Honduras: { name: 'Honduras', value: 'Honduras' },
  Hongrie: { name: 'Hongrie', value: 'Hongrie' },
  Îles_Marshall: { name: 'Îles Marshall', value: 'Îles Marshall' },
  Inde: { name: 'Inde', value: 'Inde' },
  Indonésie: { name: 'Indonésie', value: 'Indonésie' },
  Irak: { name: 'Irak', value: 'Irak' },
  Iran: { name: 'Iran', value: 'Iran' },
  Irlande: { name: 'Irlande', value: 'Irlande' },
  Islande: { name: 'Islande', value: 'Islande' },
  Israël: { name: 'Israël', value: 'Israël' },
  Italie: { name: 'Italie', value: 'Italie' },
  Jamaïque: { name: 'Jamaïque', value: 'Jamaïque' },
  Japon: { name: 'Japon', value: 'Japon' },
  Jordanie: { name: 'Jordanie', value: 'Jordanie' },
  Kazakhstan: { name: 'Kazakhstan', value: 'Kazakhstan' },
  Kenya: { name: 'Kenya', value: 'Kenya' },
  Kirghizistan: { name: 'Kirghizistan', value: 'Kirghizistan' },
  Kiribati: { name: 'Kiribati', value: 'Kiribati' },
  Kosovo: { name: 'Kosovo', value: 'Kosovo' },
  Koweït: { name: 'Koweït', value: 'Koweït' },
  Laos: { name: 'Laos', value: 'Laos' },
  Lesotho: { name: 'Lesotho', value: 'Lesotho' },
  Lettonie: { name: 'Lettonie', value: 'Lettonie' },
  Liban: { name: 'Liban', value: 'Liban' },
  Libéria: { name: 'Libéria', value: 'Libéria' },
  Libye: { name: 'Libye', value: 'Libye' },
  Liechtenstein: { name: 'Liechtenstein', value: 'Liechtenstein' },
  Lituanie: { name: 'Lituanie', value: 'Lituanie' },
  Luxembourg: { name: 'Luxembourg', value: 'Luxembourg' },
  Macédoine_du_Nord: { name: 'Macédoine du Nord', value: 'Macédoine du Nord' },
  Madagascar: { name: 'Madagascar', value: 'Madagascar' },
  Malaisie: { name: 'Malaisie', value: 'Malaisie' },
  Malawi: { name: 'Malawi', value: 'Malawi' },
  Maldives: { name: 'Maldives', value: 'Maldives' },
  Mali: { name: 'Mali', value: 'Mali' },
  Malte: { name: 'Malte', value: 'Malte' },
  Maroc: { name: 'Maroc', value: 'Maroc' },
  Maurice: { name: 'Maurice', value: 'Maurice' },
  Mauritanie: { name: 'Mauritanie', value: 'Mauritanie' },
  Mexique: { name: 'Mexique', value: 'Mexique' },
  Micronésie: { name: 'Micronésie', value: 'Micronésie' },
  Moldavie: { name: 'Moldavie', value: 'Moldavie' },
  Monaco: { name: 'Monaco', value: 'Monaco' },
  Mongolie: { name: 'Mongolie', value: 'Mongolie' },
  Monténégro: { name: 'Monténégro', value: 'Monténégro' },
  Mozambique: { name: 'Mozambique', value: 'Mozambique' },
  Namibie: { name: 'Namibie', value: 'Namibie' },
  Nauru: { name: 'Nauru', value: 'Nauru' },
  Népal: { name: 'Népal', value: 'Népal' },
  Nicaragua: { name: 'Nicaragua', value: 'Nicaragua' },
  Niger: { name: 'Niger', value: 'Niger' },
  Nigéria: { name: 'Nigéria', value: 'Nigéria' },
  Norvège: { name: 'Norvège', value: 'Norvège' },
  Nouvelle_Zélande: { name: 'Nouvelle-Zélande', value: 'Nouvelle-Zélande' },
  Oman: { name: 'Oman', value: 'Oman' },
  Ouganda: { name: 'Ouganda', value: 'Ouganda' },
  Ouzbékistan: { name: 'Ouzbékistan', value: 'Ouzbékistan' },
  Pakistan: { name: 'Pakistan', value: 'Pakistan' },
  Palaos: { name: 'Palaos', value: 'Palaos' },
  Panama: { name: 'Panama', value: 'Panama' },
  Papouasie_Nouvelle_Guinée: { name: 'Papouasie-Nouvelle-Guinée', value: 'Papouasie-Nouvelle-Guinée' },
  Paraguay: { name: 'Paraguay', value: 'Paraguay' },
  Pays_Bas: { name: 'Pays-Bas', value: 'Pays-Bas' },
  Pérou: { name: 'Pérou', value: 'Pérou' },
  Philippines: { name: 'Philippines', value: 'Philippines' },
  Pologne: { name: 'Pologne', value: 'Pologne' },
  Portugal: { name: 'Portugal', value: 'Portugal' },
  Qatar: { name: 'Qatar', value: 'Qatar' },
  République_Démocratique_du_Congo: { name: 'République démocratique du Congo', value: 'République démocratique du Congo' },
  République_dominicaine: { name: 'République dominicaine', value: 'République dominicaine' },
  République_tchèque: { name: 'République tchèque', value: 'République tchèque' },
  Roumanie: { name: 'Roumanie', value: 'Roumanie' },
  Royaume_Uni: { name: 'Royaume-Uni', value: 'Royaume-Uni' },
  Russie: { name: 'Russie', value: 'Russie' },
  Rwanda: { name: 'Rwanda', value: 'Rwanda' },
  Saint_Kitts_et_Nevis: { name: 'Saint-Kitts-et-Nevis', value: 'Saint-Kitts-et-Nevis' },
  Saint_Marin: { name: 'Saint-Marin', value: 'Saint-Marin' },
  Saint_Vincent_et_les_Grenadines: { name: 'Saint-Vincent-et-les-Grenadines', value: 'Saint-Vincent-et-les-Grenadines' },
  Sainte_Lucie: { name: 'Sainte-Lucie', value: 'Sainte-Lucie' },
  Salomon: { name: 'Salomon', value: 'Salomon' },
  Salvador: { name: 'Salvador', value: 'Salvador' },
  Samoa: { name: 'Samoa', value: 'Samoa' },
  Sao_Tomé_et_Principe: { name: 'Sao Tomé-et-Principe', value: 'Sao Tomé-et-Principe' },
  Sénégal: { name: 'Sénégal', value: 'Sénégal' },
  Serbie: { name: 'Serbie', value: 'Serbie' },
  Seychelles: { name: 'Seychelles', value: 'Seychelles' },
  Sierra_Leone: { name: 'Sierra Leone', value: 'Sierra Leone' },
  Singapour: { name: 'Singapour', value: 'Singapour' },
  Slovaquie: { name: 'Slovaquie', value: 'Slovaquie' },
  Slovénie: { name: 'Slovénie', value: 'Slovénie' },
  Somalie: { name: 'Somalie', value: 'Somalie' },
  Soudan: { name: 'Soudan', value: 'Soudan' },
  Soudan_du_Sud: { name: 'Soudan du Sud', value: 'Soudan du Sud' },
  Sri_Lanka: { name: 'Sri Lanka', value: 'Sri Lanka' },
  Suède: { name: 'Suède', value: 'Suède' },
  Suisse: { name: 'Suisse', value: 'Suisse' },
  Suriname: { name: 'Suriname', value: 'Suriname' },
  Syrie: { name: 'Syrie', value: 'Syrie' },
  Tadjikistan: { name: 'Tadjikistan', value: 'Tadjikistan' },
  Tanzanie: { name: 'Tanzanie', value: 'Tanzanie' },
  Tchad: { name: 'Tchad', value: 'Tchad' },
  Thaïlande: { name: 'Thaïlande', value: 'Thaïlande' },
  Timor_Oriental: { name: 'Timor oriental', value: 'Timor oriental' },
  Togo: { name: 'Togo', value: 'Togo' },
  Tonga: { name: 'Tonga', value: 'Tonga' },
  Trinité_et_Tobago: { name: 'Trinité-et-Tobago', value: 'Trinité-et-Tobago' },
  Tunisie: { name: 'Tunisie', value: 'Tunisie' },
  Turkménistan: { name: 'Turkménistan', value: 'Turkménistan' },
  Turquie: { name: 'Turquie', value: 'Turquie' },
  Tuvalu: { name: 'Tuvalu', value: 'Tuvalu' },
  Ukraine: { name: 'Ukraine', value: 'Ukraine' },
  Uruguay: { name: 'Uruguay', value: 'Uruguay' },
  Vanuatu: { name: 'Vanuatu', value: 'Vanuatu' },
  Vatican: { name: 'Vatican', value: 'Vatican' },
  Venezuela: { name: 'Venezuela', value: 'Venezuela' },
  Vietnam: { name: 'Vietnam', value: 'Vietnam' },
  Yémen: { name: 'Yémen', value: 'Yémen' },
  Zambie: { name: 'Zambie', value: 'Zambie' },
  Zimbabwe: { name: 'Zimbabwe', value: 'Zimbabwe' }
};
  
export interface PaysOption {
  name: string;
  value: string;
}
